name: fichar_horas_trabajo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/fondo_ficharHoras.jpg